name = "poule-poulette-audit"
compatibility_date = "2024-01-15"

[env.production]
vars = { NODE_ENV = "production" }

[[env.production.vars]]
NEXT_PUBLIC_SUPABASE_URL = "https://kauerobifkgjvddyrkuz.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthdWVyb2JpZmtnanZkZHlya3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTIxODQsImV4cCI6MjA3NDcyODE4NH0.GqMYsz9byBYHw_fqmPYH53E4fyciz3MpdUtDQDhpvd8"
